config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index, :show, :update] do
    member do
      get :cancel
    end
  end

  resources :bikes, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create]
  end

  namespace :owner do
    resources :bikes, only: [:index] do
      member do
        get :profile
      end
    end
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many_attached :photos
  has_many :bookings
  belongs_to :user

  # include AlgoliaSearch

  # searchkick

  # include PgSearch::Model
  # pg_search_scope :global_search, against: [
  #   [:address, 'A'],
  #   [:name, 'B'],
  #   [:kind, 'C']
  # ], using: {
  #   tsearch: { prefix: true }
  # }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description, :address ],
    using: {
      tsearch: { prefix: true }
    }

  KIND = ["Mountain bike", "Electric", "Electric mountain bike", "Road bike", "Dutch bike", "BMX"]

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :kind, inclusion: { in: KIND }, presence: true
  validates :name, :description, :address, :price_per_day, :size, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  STATUS = ["Pending", "Accepted", "Canceled"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :bikes
  has_many :owner_bookings, through: :bikes, source: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  # https://github.com/heartcombo/devise#strong-parameters <= Doc
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @bikes = Bike.all

    # GEOBOX MAP & MARKERS
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
        image_url: helpers.asset_url('marker.png')
      }
    end

    # SEARCH FORM
    if params[:query].present?
      sql_query = "name ILIKE :query OR address ILIKE :query OR kind ILIKE :query"
      @bikes = Bike.where(sql_query, query: "%#{params[:query]}%")
    else
      @bikes = Bike.all
    end
  end

  def show
    @bike = Bike.find(params[:id])

    # @markers = [
    #   {
    #     lat: @bike.latitude,
    #     lng: @bike.longitude,
    #     info_window: render_to_string(partial: "info_window", locals: { bike: @bike })
    #   }
    # ]
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    @bike.save!
    redirect_to owner_bikes_path
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:id])
    @bike.update(bike_params)
    redirect_to owner_bikes_path
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to owner_bikes_path
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :description, :address, :size, :kind, :price_per_day, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all.where(user: current_user)

    @bookings_accepted = @bookings.where(status: "Accepted")
    @bookings_pending = @bookings.where(status: "Pending")
    @bookings_canceled = @bookings.where(status: "Canceled")
  end

  def new
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @bike = Bike.find(params[:bike_id])
    @booking.bike = @bike
    @booking.user = current_user
    @booking.save!

    redirect_to bookings_path
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def patch
    @booking = Booking.find(params[:id])
    @booking.status = "Canceled"
    @booking.save!
    redirect_to bookings_path
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = params[:booking][:status]
    @booking.save!
    redirect_to owner_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:bike_id, :start_at, :end_at, :status)
  end
end

app/controllers/owner/bikes_controller.rb
class Owner::BikesController < ApplicationController
  def index
    @owner_bikes = current_user.bikes.all
    @owner_bike = Bike.new
  end
  
  def profile
    @owner = current_user
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @owner_bikes = Bike.all.where(user: current_user)
    @owner_bookings_canceled = []
    @owner_bookings_accepted = []
    @owner_bookings_pending = []
    @owner_bikes.each do |bike|
      bike.bookings.each do |bike_booking|
        @owner_bookings_canceled << bike_booking if bike_booking.status == "Canceled"
        @owner_bookings_accepted << bike_booking if bike_booking.status == "Accepted"
        @owner_bookings_pending << bike_booking if bike_booking.status == "Pending"
      end
    end

  end
end




# <%= @owner_bookings_canceled.size %>
# <%= @owner_bookings_accepted.size %>
# <%= @owner_bookings_pending.size %>

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @bikes = Bike.all

    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
        image_url: helpers.asset_url('marker.png')
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form_flat_pickr.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Flatpickr Demo</h2>

    <%= simple_form_for :search, method: "get" do |f| %>
      <%= f.input :starts_at, as: :string, required: false, input_html: {id: "range_start"} %>
      <%= f.button :submit, "Go", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bikes/_info_window.html.erb
<h2><%= bike.name %></h2>
<p><%= bike.address %></p>
<%= link_to "", bike_path(bike), class: "stretched-link" %>

app/views/bikes/edit.html.erb
<div class="form-edit">
  <%= simple_form_for(@bike) do |f| %>
    <div class="form-group bg-light p-4">
      <h1 class="text-center"><%= "Bike edit" %></h1>
      <div class="d-flex justify-content-between">
        <%= f.input :name, class:"form-control" %>
        <%= f.input :size, class:"form-control" %>
        <%= f.input :kind, collection: Bike::KIND, class:"form-control" %>
      </div>
      <%= f.input :address, class:"form-control" %>
      <%= f.input :description, class:"form-control" %>
      <%= f.input :price_per_day, class:"form-control" %>
      <div class="d-flex justify-content-between align-items-center">
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Update my bike !", class: "btn btn-info"%>
      </div>
    </div>
  <% end %>
</div>

app/views/bikes/index.html.erb
<div class="row g-0">
  <div class="container col-6">
    <div>

      <div class="my-form col-md-12">
        <%= form_tag bikes_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          required: true,
          class: "my-form-input form-control col-md-10 col-sm-9",
          placeholder: "Find your bike" %>
        <%= submit_tag "Search", class: "my-form-button btn btn-info col-md-2 col-sm-3" %>
        <% end %>

    </div>
      <% @bikes.each do |bike| %>
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
              <%= cl_image_tag bike.photos[0].key, height: 300, width: 400, crop: :fill, class: "img-fluid rounded-start" %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <div class="d-flex p-1 justify-content-between">
                  <div class="title-and-kind flex-right">
                    <h5 class="card-title m-0 font-weight-bold"><%= bike.name %></h5>
                    <p class="card-title"><small><%= bike.kind %></small></p>
                  </div>
                  <p class="user-name card-text"><small class="text-muted"><%= bike.user.first_name %> <%= bike.user.last_name.upcase %>&nbsp;&nbsp;<i class="fas fa-user-alt"></i></small></p>
                </div>
                <p class="card-text bike-description"><%= bike.description %></p>
                <div class="price-card d-flex flex-row-reverse">
                  <%= link_to "view more", bike_path(bike), class: "btn btn-sm btn-info" %>
                  <p class="m-0 pr-3"><%= bike.price_per_day %>€/Day</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
    <div class="col-5 content-right">
        <div id="map"
          style="width: 100%; height: 100vh;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<div class="row justify-content-md-center mt-3">

  <div class="col-md-10 p-0 d-flex justify-content-md-center mt-4 position-relative">

    <div class="content-img col-md-5">
    <%= link_to "< back to index", bikes_path, class: "text-info back_to_index" %>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= cl_image_tag @bike.photos[0].key, crop: :fill %>
            </div>
            <% unless @bike.photos[1].nil? %>
              <div class="carousel-item">
                <%= cl_image_tag @bike.photos[1].key, crop: :fill %>
              </div>
              <div class="carousel-item">
                <%= cl_image_tag @bike.photos[2].key, crop: :fill %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </button>
        </div>
    </div>
    <div class="content-right col-md-5 p-3 pl-5">
      <div class="content-name-price d-flex justify-content-between border-bottom">
        <h2><strong><%= @bike.name %></strong></h2>
        <span class="d-flex align-items-end text-info"><h2><strong><%= @bike.price_per_day %>€</strong></h2>&nbsp;<h4>/day</h4></span>
      </div>
      <div class="content-description">
        <div class="bike-rating d-flex w-100 pt-3">
          <i class="fas fa-star text-info "></i>
          <i class="fas fa-star text-info "></i>
          <i class="fas fa-star text-info "></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <p class="m-0"><!--Here Rating-->3.9/5</p><%= link_to 'See all reviews' , bikes_path , class: "ml-3"%>
        </div>
        <div class="bike-description pt-3">
          <p><%= @bike.description %></p>
        </div>
        <div class="bike-kind">
          <span class="d-flex"><%= image_tag ("bike_show/biking-solid.svg"), height: "20px" %> <p class="ml-3"><%= @bike.kind %></p></span>
        </div>
        <div class="bike-size">
          <span class="d-flex"><%= image_tag ("bike_show/arrows-alt-v-solid.svg"), height: "20px" %> <p class="ml-3"><%= @bike.size %>ch</p></span>
        </div>
        <div class="bike-address">
          <span class="d-flex"><%= image_tag ("bike_show/map-marker-alt-solid.svg"), height: "20px" %> <p class="ml-3"><%= @bike.address %></p></span>
        </div>
        <div class="bike-options">
          <span class="d-flex"><strong><p>Options : </p></strong>
            <%= image_tag ("bike_show/protective.png"), height: "25px", class: "ml-3" %>
            <%= image_tag ("bike_show/pump.png"), height: "25px", class: "ml-3" %>
            <%= image_tag ("bike_show/child.png"), height: "25px", class: "ml-3" %>
          </span>
        </div>

      </div>
      <div class="content-booking border-top mt-2">
        <h2 class="mt-3">Booking this bike</h2>


        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
          <%= simple_form_for [@bike, @bike.bookings.new] do |f| %>
            <span class="d-flex justify-content-between">
            <%= f.input :start_at, as: :string, required: false, input_html: {class: "datepicker", id: "start-date"} %>
            <%= f.input :end_at, as: :string, required: false, input_html: {class: "datepicker", id: "end-date"} %>
            </span>
            <h3 id="total-price" data-priceperday="<%= @bike.price_per_day %>" class="mt-3 font-weight-bold text-info text-right"></h3>
            <%= f.button :submit, "Book now !", class: "btn btn-info rounded w-100 mt-3 h-25" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/cancel.html.erb
<h1>Bookings#cancel</h1>
<p>Find me in app/views/bookings/cancel.html.erb</p>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGoodBike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <link rel="icon" type="image/png"
    href="https://res.cloudinary.com/terence/image/upload/v1637852829/The%20Good%20Bike/favicon_jkdmtf.png" />
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if current_page?(root_path) %>
      <%= render 'shared/navbar' %>
      <% elsif user_signed_in? && current_page?(profile_owner_bike_path(current_user)) %>
      <%= render 'shared/navbar_dashboard' %>
    <% else %>
      <%= render 'shared/navbar_pages' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>
    <%= yield %>
  <footer>
    <%= render 'shared/footer' %>
  </footer>
  </body>
</html>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

app/views/owner/bikes/index.html.erb
<div class="container col-7 mt-2">


  <div>
      <% @owner_bikes.each.reverse_each do |owner_bike| %>
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
            <%if owner_bike.photos.present?%>
              <%= cl_image_tag owner_bike.photos[0].key, height: 300, width: 400, crop: :fill, class: "img-fluid rounded-start" %>
            <% else %>
              <%= image_tag 'no-image-available.png', height: 300, width: 400, crop: :fill, class: "img-fluid rounded-start" %>
            <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <div class="d-flex p-1 justify-content-between">
                  <h5 class="card-title"><%= owner_bike.name %></h5>
                  <p class="user-name card-text"><small class="text-muted"><%= owner_bike.kind %></small></p>
                </div>
                <p class="card-text bike-description"><%= owner_bike.description %></p>
                <div class="price-card d-flex flex-row-reverse">
                  <p class="m-0 pr-3"><%= owner_bike.price_per_day %>€/Day</p>
                </div>
                <div class="text-decoration-none">
                  <%= link_to '<i class="edit-icon far fa-edit mr-3"></i>'.html_safe, edit_bike_path(owner_bike) %>
                  <%= link_to bike_path(owner_bike),  method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="delete-icon fas fa-trash-alt"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="form-bike">
    <%= simple_form_for(@owner_bike) do |f| %>
      <div class="form-group bg-light pt-2 pl-4 pr-4">
        <h1 class="text-center"><%= "Add a bike" %></h1>
        <div class="d-flex justify-content-between">
          <%= f.input :name, class:"form-control" %>
          <%= f.input :size, class:"form-control" %>
          <%= f.input :kind, collection: Bike::KIND, class:"form-control" %>
        </div>
        <%= f.input :address, class:"form-control" %>
        <%= f.input :description, class:"form-control" %>
        <%= f.input :price_per_day, class:"form-control" %>
        <div class="d-flex justify-content-between align-items-center">
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit "Add my bike !", class: "btn btn-info"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_info_window.html.erb
<h2><%= bike.name %></h2>
<p><%= bike.address %></p>
<%= link_to "", bike_path(bike), class: "stretched-link" %>

app/views/pages/home.html.erb
<%# Div en tant que background %>
<div class="geo-form"></div>

<div class="container py-3">

  <%= link_to root_path, class:"navbar-brand w-100" do %>
    <h1  class="d-flex align-items-end", style="cursor: default">THE G<lottie-player class="my-lottie-logo" src="https://assets7.lottiefiles.com/packages/lf20_uvovx5gl.json"  background="transparent"  speed="1"  style="width: 320px; height: 320px;" loop autoplay ></lottie-player>D BIKE</h1>
  <% end %>

  <div class="w-100 align-items-center mx-auto sticky">
    <div class="searching-form d-flex w-100 justify-content-center">
      <%= form_tag bikes_path, method: "GET", class:"p-3 form-inline" do %>
        <div>
          <%= text_field_tag :query,
          params[:query],
          required: false,
          class: "my-form-input-kind form-control",
          placeholder: "Find your bike" %>
        </div>
        <div>
          <%= text_field_tag :query,
          params[:query],
          required: true,
          class: "my-form-input-address form-control",
          placeholder: "Where do you go ?" %>
        </div>
        <%=  submit_tag "Search", class:"btn btn-info"%>
      <% end %>
    </div>
  </div>

  <div class="arrow-down bounce d-flex justify-content-center align-items-center"><i class="fas fa-caret-down"></i></div>




  <div class="tuto text-center col-12 mt-4">
  <div class="mt-5 mb-5">
    <h2>How it works</h2>
      <h6><strong>The good bike helps people to rent bikes all over the world</strong></h6>
      <p class="col-12 col-lg-7 mx-auto">The good bike is a bike rental and sharing service that provides a platform to connect bike owners with people looking to rent bike around the world.</p>
    </div>
    <div class="container">
      <div class="row d-flex justify-content-around">
        <div class="card-category overflow-hidden text-center col-lg-3 col-12 ">
          <lottie-player src="https://assets7.lottiefiles.com/packages/lf20_ko53b4tp.json"  background="transparent"  speed="1"  style="height: 200px;"  loop  autoplay></lottie-player>
          <hr>
          <p>Find your ideal bike for your needs, any type, anywhere near you.</p>
        </div>
        <div class="card-category overflow-hidden col-lg-3 col-12">
          <lottie-player src="https://assets1.lottiefiles.com/packages/lf20_ytg7s6tx.json"  background="transparent"  speed="1"  style="height: 200px;"  loop  autoplay></lottie-player>
          <hr>
          <p>Choose your dates of use and book it in a few clicks.</p>
        </div>
        <div class="card-category overflow-hidden col-lg-3 col-12">
          <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_lnji2epm.json"  background="transparent"  speed="1"  style="height: 200px;"  loop  autoplay></lottie-player>
          <hr>
          <p>Pick up the bike, enjoy it and pay for the service after use.</p>
        </div>
        <div class="card-category overflow-hidden col-lg-3 col-12">
          <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_1H7IW0.json"  background="transparent"  speed="1"  style="height: 200px;"  loop  autoplay></lottie-player>
          <hr>
          <p>Put your bike online, and rent it at the price you want.</p>
        </div>
      </div>
    </div>
  </div>

  <br>
  <br>
  <br>
  <br>

  <%# Put a map with all offers in france(exemple) without filter kind %>
  <div class="container">
    <div id="map"
      style="width: 100%; height: 400px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="#"><i class="fab fa-github"></i></a>
    dev by Diamond team - <%= Time.now.year %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="d-flex justify-content-end">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav mr-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          <%# </li> %>
          <%# <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          <%# </li> %>
          <%# <li class="nav-item dropdown"> %>
            <%# <%= image_tag "https://mystickermania.com/cdn/stickers/cartoons/sticker_5031-512x512.png?t=09102020", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", profile_owner_bike_path(current_user), class: "dropdown-item" %>
              <%# <%= link_to "My bikes", owner_bikes_path, class: "dropdown-item" %>
              <%# <%= link_to "My bookings", owner_bookings_path, class: "dropdown-item" %>
              <%# <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%# </div> %>
          <%# </li> %>
          <%= link_to profile_owner_bike_path(current_user) do %>
            <%= image_tag "https://mystickermania.com/cdn/stickers/cartoons/sticker_5031-512x512.png?t=09102020", class: "avatar" %>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_dashboard.html.erb
<nav class="navbar navbar-light navbar-expand-sm navbar-lewagon_pages">
  <div class="container-fluid">
    <%= link_to "The good bike", root_path, {style:"color:rgb(161, 193, 125); font-size:28px; font-family: 'Comfortaa', cursive;"}%>
    <div class="d-flex">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link me-2 text-secondary" %>
        <%= link_to profile_owner_bike_path(current_user) do %>
        <%= image_tag "https://mystickermania.com/cdn/stickers/cartoons/sticker_5031-512x512.png?t=09102020", class: "avatar" %>
        <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navbar_pages.html.erb
<nav class="navbar navbar-light navbar-expand-sm navbar-lewagon_pages">
  <div class="container-fluid">
  <% if user_signed_in? %>
    <%= link_to "The good bike", root_path, {style:"color:rgb(161, 193, 125); font-size:28px; font-family: 'Comfortaa', cursive;"} %>
    <%# <div class="d-flex"> %>
      <%# <%= link_to "Bookings", bookings_path, class: "nav-link me-2 text-secondary"%>
      <%# <div class="nav-item dropdown"> %>
        <%# <%= image_tag "https://mystickermania.com/cdn/stickers/cartoons/sticker_5031-512x512.png?t=09102020", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%# <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"> %>
          <%# <%= link_to "My profile", profile_owner_bike_path(current_user), class: "dropdown-item" %>
          <%# <%= link_to "My bikes", owner_bikes_path, class: "dropdown-item" %>
          <%# <%= link_to "My bookings", owner_bookings_path, class: "dropdown-item" %>
          <%# <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <%# </div> %>
      <%# </div> %>
    <%# </div> %>
      <%= link_to profile_owner_bike_path(current_user) do %>
        <%= image_tag "https://mystickermania.com/cdn/stickers/cartoons/sticker_5031-512x512.png?t=09102020", class: "avatar" %>
      <% end %>
    <% else %>
      <%= link_to "The good bike", root_path, {style:"color:rgb(161, 193, 125); font-size:28px; font-family: 'Comfortaa', cursive;"}%>
      <%= link_to "Login", new_user_session_path, class: "nav-link me-2 text-secondary" %>
    <% end %>
  </div>
</nav>